# Generated by Django 2.2.11 on 2022-10-07 12:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from ..utils import rounded

@rounded
def get_price_for_time_range(product, reservation):
    begin = reservation.begin
    end = reservation.end
    assert begin < end

    if product.price_type == 'fixed':
        return product.price
    elif product.price_type == 'per_period':
        assert product.price_period, '{} {}'.format(product, product.price_period)
        return product.price * Decimal((end - begin) / product.price_period)


def populate_prices_in_order(apps, schema_editor):
    OrderLine = apps.get_model('payments', 'OrderLine')
    for order_line in OrderLine.objects.all():
        unit_price = get_price_for_time_range(order_line.product, order_line.order.reservation)
        order_line.unit_price = unit_price
        order_line.total_price = unit_price * order_line.quantity
        order_line.save()

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total price including VAT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit price including VAT'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_prices_in_order, migrations.RunPython.noop),
    ]
