# Generated by Django 2.2.11 on 2022-10-20 06:32

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_price_to_order_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_percentage',
        ),
        migrations.AddField(
            model_name='orderline',
            name='price_period',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True, verbose_name='price period'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='price_type',
            field=models.CharField(choices=[('per_period', 'per period'), ('fixed', 'fixed')], default='per_period', max_length=32, verbose_name='price type'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='tax_percentage',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0.00'), (Decimal('10.00'), '10.00'), (Decimal('14.00'), '14.00'), (Decimal('24.00'), '24.00')], decimal_places=2, default=Decimal('24.00'), max_digits=5, verbose_name='tax percentage'),
        ),
    ]
