# Generated by Django 2.2.11 on 2023-05-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_move_product_fields_to_orderline"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_link",
            field=models.URLField(blank=True, verbose_name="Payment Link"),
        ),
    ]
