# Generated by Django 2.2.11 on 2023-08-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_order_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=255, verbose_name="SKU"),
        ),
    ]
