# Generated by Django 2.2.11 on 2023-10-16 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_product_sku_allow_blank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("xml", models.TextField(blank=True, verbose_name="XML")),
                (
                    "xml_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Invoice XML generated at"
                    ),
                ),
                (
                    "sent_to_sap_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sent to SAP at"
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="payments.Invoice",
                verbose_name="invoice",
            ),
        ),
    ]
