# Generated by Django 2.2.11 on 2023-11-02 11:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_product_sku_allow_blank"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAPIncomeAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Identifier"
                    ),
                ),
            ],
            options={
                "verbose_name": "SAP Income Account",
                "verbose_name_plural": "SAP Income Accounts",
            },
        ),
        migrations.CreateModel(
            name="SAPMaterialCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0.00"),
                            (Decimal("10.00"), "10.00"),
                            (Decimal("14.00"), "14.00"),
                            (Decimal("24.00"), "24.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("24.00"),
                        max_digits=5,
                        verbose_name="tax percentage",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(max_length=18, verbose_name="SAP Material Code"),
                ),
                (
                    "sap_income_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sap_material_codes",
                        to="payments.SAPIncomeAccount",
                        verbose_name="SAP Income Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAP Material Code",
                "verbose_name_plural": "SAP Material Codes",
                "ordering": ("material_code",),
            },
        ),
    ]
