# Generated by Django 2.2.11 on 2023-10-03 12:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kulkunen", "0002_add_install_at_and_remove_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesscontrolsystem",
            name="driver",
            field=models.CharField(
                choices=[
                    ("sipass", "Siemens SiPass"),
                    ("securitas", "Securitas Bitwards"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="accesscontrolsystem",
            name="driver_config",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, help_text="Driver-specific configuration", null=True
            ),
        ),
    ]
