# Generated by Django 3.2.25 on 2025-02-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulkunen', '0003_auto_20231003_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrolgrant',
            name='driver_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrolresource',
            name='driver_config',
            field=models.JSONField(blank=True, help_text='Driver-specific configuration', null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrolresource',
            name='driver_data',
            field=models.JSONField(editable=False, help_text='Internal driver data', null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrolsystem',
            name='driver_config',
            field=models.JSONField(blank=True, help_text='Driver-specific configuration', null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrolsystem',
            name='driver_data',
            field=models.JSONField(editable=False, help_text='Internal driver data', null=True),
        ),
        migrations.AlterField(
            model_name='accesscontroluser',
            name='driver_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
