# Generated by Django 2.2.11 on 2022-10-11 06:41

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import respa_pricing.models.price


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_add_price_to_order_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            bases=(respa_pricing.models.price.AutoIdentifiedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            bases=(respa_pricing.models.price.AutoIdentifiedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserGroupPriceListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price including VAT')),
                ('tax_percentage', models.DecimalField(choices=[(Decimal('0.00'), '0.00'), (Decimal('10.00'), '10.00'), (Decimal('14.00'), '14.00'), (Decimal('24.00'), '24.00')], decimal_places=2, default=Decimal('24.00'), max_digits=5, verbose_name='tax percentage')),
                ('price_period', models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True, verbose_name='price period')),
                ('price_type', models.CharField(choices=[('per_period', 'per period'), ('fixed', 'fixed')], default='per_period', max_length=32, verbose_name='price type')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_prices', to='respa_pricing.PriceList')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelist_items', to='respa_pricing.UserGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priced_products', to='respa_pricing.PriceList')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.Product')),
            ],
        ),
        migrations.CreateModel(
            name='EventPriceListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price including VAT')),
                ('tax_percentage', models.DecimalField(choices=[(Decimal('0.00'), '0.00'), (Decimal('10.00'), '10.00'), (Decimal('14.00'), '14.00'), (Decimal('24.00'), '24.00')], decimal_places=2, default=Decimal('24.00'), max_digits=5, verbose_name='tax percentage')),
                ('price_period', models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True, verbose_name='price period')),
                ('price_type', models.CharField(choices=[('per_period', 'per period'), ('fixed', 'fixed')], default='per_period', max_length=32, verbose_name='price type')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelist_items', to='respa_pricing.Event')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_prices', to='respa_pricing.PriceList')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
