# Generated by Django 2.2.11 on 2023-03-20 11:57

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import respa_pricing.models.price


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0003_move_product_fields_to_orderline"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Event type",
                "verbose_name_plural": "Event types",
            },
            bases=(respa_pricing.models.price.AutoIdentifiedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Price list",
                "verbose_name_plural": "Price lists",
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
            ],
            options={
                "verbose_name": "User group",
                "verbose_name_plural": "User groups",
            },
            bases=(respa_pricing.models.price.AutoIdentifiedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="UserGroupPriceListItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="price including VAT",
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0.00"),
                            (Decimal("10.00"), "10.00"),
                            (Decimal("14.00"), "14.00"),
                            (Decimal("24.00"), "24.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("24.00"),
                        max_digits=5,
                        verbose_name="tax percentage",
                    ),
                ),
                (
                    "price_period",
                    models.DurationField(
                        blank=True,
                        default=datetime.timedelta(0, 3600),
                        null=True,
                        verbose_name="price period",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[("per_period", "per period"), ("fixed", "fixed")],
                        default="per_period",
                        max_length=32,
                        verbose_name="price type",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usergroup_prices",
                        to="respa_pricing.PriceList",
                        verbose_name="price list",
                    ),
                ),
                (
                    "user_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricelist_items",
                        to="respa_pricing.UserGroup",
                        verbose_name="user group",
                    ),
                ),
            ],
            options={
                "verbose_name": "User group price",
                "verbose_name_plural": "User group prices",
            },
        ),
        migrations.CreateModel(
            name="PricedProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priced_products",
                        to="respa_pricing.PriceList",
                        verbose_name="price list",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priced product",
                "verbose_name_plural": "Priced products",
            },
        ),
        migrations.CreateModel(
            name="EventTypePriceListItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="price including VAT",
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0.00"),
                            (Decimal("10.00"), "10.00"),
                            (Decimal("14.00"), "14.00"),
                            (Decimal("24.00"), "24.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("24.00"),
                        max_digits=5,
                        verbose_name="tax percentage",
                    ),
                ),
                (
                    "price_period",
                    models.DurationField(
                        blank=True,
                        default=datetime.timedelta(0, 3600),
                        null=True,
                        verbose_name="price period",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[("per_period", "per period"), ("fixed", "fixed")],
                        default="per_period",
                        max_length=32,
                        verbose_name="price type",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricelist_items",
                        to="respa_pricing.EventType",
                        verbose_name="event type",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_prices",
                        to="respa_pricing.PriceList",
                        verbose_name="price list",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event type price",
                "verbose_name_plural": "Event type prices",
            },
        ),
    ]
