# Generated by Django 2.2.11 on 2022-10-20 08:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpricelistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price including VAT'),
        ),
        migrations.AlterField(
            model_name='usergrouppricelistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price including VAT'),
        ),
    ]
