# Generated by Django 2.2.11 on 2023-03-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("respa_pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricedproduct",
            name="price_list",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priced_product",
                to="respa_pricing.PriceList",
            ),
        ),
    ]
