# Generated by Django 2.2.11 on 2023-04-18 07:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("respa_pricing", "0002_pricedproduct_price_list_onetoone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventtypepricelistitem",
            name="tax_percentage",
        ),
        migrations.RemoveField(
            model_name="usergrouppricelistitem",
            name="tax_percentage",
        ),
        migrations.AddField(
            model_name="eventtype",
            name="tax_percentage",
            field=models.DecimalField(
                choices=[
                    (Decimal("0.00"), "0.00"),
                    (Decimal("10.00"), "10.00"),
                    (Decimal("14.00"), "14.00"),
                    (Decimal("24.00"), "24.00"),
                ],
                decimal_places=2,
                default=Decimal("24.00"),
                max_digits=5,
                verbose_name="tax percentage",
            ),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="tax_percentage",
            field=models.DecimalField(
                choices=[
                    (Decimal("0.00"), "0.00"),
                    (Decimal("10.00"), "10.00"),
                    (Decimal("14.00"), "14.00"),
                    (Decimal("24.00"), "24.00"),
                ],
                decimal_places=2,
                default=Decimal("24.00"),
                max_digits=5,
                verbose_name="tax percentage",
            ),
        ),
    ]
