# Generated by Django 2.2.11 on 2022-10-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_pricing', '0002_auto_20221020_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='needs_manual_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
