# Generated by Django 2.2.11 on 2022-11-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_pricing', '0003_pricelist_needs_manual_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespaPaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('text_en', models.TextField(verbose_name='Description', blank=True)),
                ('text_fi', models.TextField(verbose_name='Description', blank=True)),
                ('text_sv', models.TextField(verbose_name='Description', blank=True)),
                ('payment_is_refundable', models.BooleanField(default=False, verbose_name='Payment is refundable')),
                ('refund_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Deductible percentage if reservation is refunded')),
                ('cancellation_min_days_in_advance', models.PositiveIntegerField(blank=True, default=0, verbose_name='The customer can cancel the reservation (days) before the reservation starts.')),
            ],
        ),
    ]
