# Generated by Django 2.2.11 on 2023-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_pricing', '0004_respapaymentterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='respapaymentterm',
            name='text',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='respapaymentterm',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='respapaymentterm',
            name='text_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='respapaymentterm',
            name='text_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
