# Generated by Django 2.2.11 on 2023-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("respa_pricing", "0004_auto_20230511_1422"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="include_other_event_type_option",
            field=models.BooleanField(
                default=True,
                help_text='Designates whether a "None of the above" option, that doesn\'t affect the price, should be added to the event type options.',
                verbose_name="include other event type option",
            ),
        ),
    ]
