# Generated by Django 2.2.11 on 2023-05-30 06:08

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respa_pricing', '0005_pricelist_include_other_event_type_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('include_other_event_type_option', models.BooleanField(default=True, help_text='Designates whether a "None of the above" option, that doesn\'t affect the price, should be added to the event type options.', verbose_name='include other event type option')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupPriceListTemplateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price including VAT')),
                ('price_period', models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True, verbose_name='price period')),
                ('price_type', models.CharField(choices=[('per_period', 'per period'), ('fixed', 'fixed')], default='per_period', max_length=32, verbose_name='price type')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_prices', to='respa_pricing.PriceListTemplate', verbose_name='template')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelist_template_items', to='respa_pricing.UserGroup', verbose_name='user group')),
            ],
            options={
                'verbose_name': 'User group price',
                'verbose_name_plural': 'User group prices',
            },
        ),
        migrations.CreateModel(
            name='EventTypePriceListTemplateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price including VAT')),
                ('price_period', models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True, verbose_name='price period')),
                ('price_type', models.CharField(choices=[('per_period', 'per period'), ('fixed', 'fixed')], default='per_period', max_length=32, verbose_name='price type')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelist_template_items', to='respa_pricing.EventType', verbose_name='event type')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_prices', to='respa_pricing.PriceListTemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'Event type price',
                'verbose_name_plural': 'Event type prices',
            },
        ),
        migrations.AddField(
            model_name='eventtypepricelistitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_prices', to='respa_pricing.EventTypePriceListTemplateItem'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='respa_pricing.PriceListTemplate'),
        ),
        migrations.AddField(
            model_name='usergrouppricelistitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_prices', to='respa_pricing.UserGroupPriceListTemplateItem'),
        ),
    ]
