# Generated by Django 2.2.11 on 2023-12-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respa_pricing', '0006_auto_20230530_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtypepricelisttemplateitem',
            options={'verbose_name': 'Event type price template', 'verbose_name_plural': 'Event type price templates'},
        ),
        migrations.AlterModelOptions(
            name='pricelisttemplate',
            options={'verbose_name': 'Price list template', 'verbose_name_plural': 'Price list templates'},
        ),
        migrations.AlterModelOptions(
            name='usergrouppricelisttemplateitem',
            options={'verbose_name': 'User group price template', 'verbose_name_plural': 'User group price templates'},
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='respa_pricing.PriceListTemplate'),
        ),
    ]
