# Generated by Django 2.2.11 on 2023-07-18 11:33

from django.db import migrations
from django.template import Template, Context

BODY_TEMPLATES = {
    "en": """
Hello,

{{ message }}

{% verbatim %}
Resource: {{ resource }}
Unit: {{ unit }}
Starts: {{ begin }}
Ends: {{ end }}
{% endverbatim %}

This is an automated message, please don't reply to this.

Best regards,

Varaamo
""",
    "fi": """
Hei,

{{ message }}

{% verbatim %}
Tila: {{ resource }}
Toimipiste: {{ unit }}
Alkaa: {{ begin }}
Loppuu: {{ end }}
{% endverbatim %}

Tämä on automaattinen viesti, joten älä vastaa tähän.

Ystävällisin terveisin,

Varaamo
""",
}

NOTIFICATIONS = [
    (
        "reservation_cancelled_official",
        (
            (
                "en",
                "Reservation cancelled",
                "A reservation has been cancelled:",
            ),
            (
                "fi",
                "Varaus peruttu",
                "Varaus on peruttu:",
            ),
        ),
    ),
    (
        "reservation_confirmed_official",
        (
            (
                "en",
                "Reservation confirmed",
                "A reservation has been confirmed:",
            ),
            (
                "fi",
                "Varaus vahvistettu",
                "Varaus on vahvistettu:",
            ),
        ),
    ),
    (
        "reservation_denied_official",
        (
            (
                "en",
                "Reservation denied",
                "A reservation has been denied:",
            ),
            (
                "fi",
                "Varaus hylätty",
                "Varaus on hylätty:",
            ),
        ),
    ),
    (
        "paid_reservation_approved_official",
        (
            (
                "en",
                "Paid reservation approved",
                "A paid reservation has been approved:",
            ),
            (
                "fi",
                "Maksettava varaus vahvistettu",
                "Maksettava varaus vahvistettu:",
            ),
        ),
    ),
]


def forwards(apps, schema_editor):
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    NotificationTemplateTranslation = apps.get_model(
        "notifications",
        "NotificationTemplateTranslation",
    )

    for notification_type, details in NOTIFICATIONS:
        notification, created = NotificationTemplate.objects.get_or_create(
            type=notification_type
        )
        if created:
            translations = []
            for language, subject, message in details:
                body = Template(BODY_TEMPLATES[language]).render(
                    Context(
                        {
                            "message": message,
                        }
                    )
                )
                translations.append(
                    NotificationTemplateTranslation(
                        master_id=notification.pk,
                        language_code=language,
                        subject=subject,
                        body=body,
                    )
                )

            NotificationTemplateTranslation.objects.bulk_create(translations)


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0008_add_new_notification_official_statuses"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
