# Generated by Django 2.2.11 on 2023-07-20 10:07

from django.db import migrations

from django.template import Template, Context

BODY_TEMPLATES = {
    "en": """
Hello,

{{ message }}

{% verbatim %}
Resource: {{ resource }}
Unit: {{ unit }}
Starts: {{ begin }}
Ends: {{ end }}
{% endverbatim %}

This is an automated message, please don't reply to this.

Best regards,

Varaamo
""",
    "fi": """
Hei,

{{ message }}

{% verbatim %}
Tila: {{ resource }}
Toimipiste: {{ unit }}
Alkaa: {{ begin }}
Loppuu: {{ end }}
{% endverbatim %}

Tämä on automaattinen viesti, joten älä vastaa tähän.

Ystävällisin terveisin,

Varaamo
""",
}

NOTIFICATIONS = [
    (
        "reservation_invoice_requested",
        (
            (
                "en",
                "Reservation requested",
                "You have requested an invoice for this reservation:",
            ),
            (
                "fi",
                "Lasku varauksesta pyydetty",
                "Olet pyytänyt laskun tästä varauksesta:",
            ),
        ),
    ),
    (
        "reservation_invoice_requested_official",
        (
            (
                "en",
                "Reservation requested",
                "An invoice for this reservation has been requested:",
            ),
            (
                "fi",
                "Lasku varauksesta pyydetty",
                "Lasku tästä varauksesta on pyydetty:",
            ),
        ),
    ),
]


def forwards(apps, schema_editor):
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    NotificationTemplateTranslation = apps.get_model(
        "notifications",
        "NotificationTemplateTranslation",
    )

    for notification_type, details in NOTIFICATIONS:
        notification, created = NotificationTemplate.objects.get_or_create(
            type=notification_type
        )
        if created:
            translations = []
            for language, subject, message in details:
                body = Template(BODY_TEMPLATES[language]).render(
                    Context(
                        {
                            "message": message,
                        }
                    )
                )
                translations.append(
                    NotificationTemplateTranslation(
                        master_id=notification.pk,
                        language_code=language,
                        subject=subject,
                        body=body,
                    )
                )

            NotificationTemplateTranslation.objects.bulk_create(translations)


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0010_add_invoice_requested_type"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
