# Generated by Django 2.2.11 on 2024-12-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0011_create_invoice_requested_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("reservation_requested", "Reservation requested"),
                    (
                        "reservation_requested_official",
                        "Reservation requested official",
                    ),
                    ("reservation_requested", "Reservation invoice requested"),
                    (
                        "reservation_requested_official",
                        "Reservation invoice requested official",
                    ),
                    ("reservation_cancelled", "Reservation cancelled"),
                    (
                        "reservation_cancelled_official",
                        "Reservation cancelled official",
                    ),
                    ("reservation_confirmed", "Reservation confirmed"),
                    (
                        "reservation_confirmed_official",
                        "Reservation confirmed official",
                    ),
                    ("reservation_created", "Reservation created"),
                    ("reservation_changed", "Reservation changed"),
                    ("reservation_denied", "Reservation denied"),
                    ("reservation_denied_official", "Reservation denied official"),
                    (
                        "reservation_created_with_access_code",
                        "Reservation created with access code",
                    ),
                    (
                        "reservation_access_code_created",
                        "Access code was created for a reservation",
                    ),
                    ("paid_reservation_approved", "Paid reservation approved"),
                    (
                        "paid_reservation_approved_official",
                        "Paid reservation approved official",
                    ),
                    ("catering_order_created", "Catering order created"),
                    ("catering_order_modified", "Catering order modified"),
                    ("catering_order_deleted", "Catering order deleted"),
                    ("reservation_comment_created", "Reservation comment created"),
                    (
                        "catering_order_comment_created",
                        "Catering order comment created",
                    ),
                    ("reservation_reminder", "Reservation reminder"),
                ],
                db_index=True,
                max_length=100,
                unique=True,
                verbose_name="Type",
            ),
        ),
    ]
