# Generated by Django 2.2.11 on 2024-12-19 08:35

from django.db import migrations
from django.template import Context, Template

BODY_TEMPLATES = {
    "en": """
Hello,

{{ message }}

{% verbatim %}
Resource: {{ resource }}
Unit: {{ unit }}
Starts: {{ begin }}
Ends: {{ end }}
{% endverbatim %}

This is an automated message, please don't reply to this.

Best regards,
Varaamo
""",
    "fi": """
Hei,

{{ message }}

{% verbatim %}
Tila: {{ resource }}
Toimipiste: {{ unit }}
Alkaa: {{ begin }}
Päättyy: {{ end }}
{% endverbatim %}

Tämä on automaattinen viesti, joten ethän vastaa tähän.

Ystävällisin terveisin,
Varaamo
""",
}


def forwards(apps, schema_editor):
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    NotificationTemplateTranslation = apps.get_model(
        "notifications",
        "NotificationTemplateTranslation",
    )

    notification, created = NotificationTemplate.objects.get_or_create(
        type="reservation_reminder"
    )
    if created:
        translations = []
        for language, subject, message in [
            (
                "en",
                "Upcoming reservation",
                "You have a reservation coming up soon:",
            ),
            (
                "fi",
                "Muistathan lähestyvän varauksesi",
                "Sinulla on pian varaus:",
            ),
        ]:
            body = Template(BODY_TEMPLATES[language]).render(
                Context(
                    {
                        "message": message,
                    }
                )
            )
            translations.append(
                NotificationTemplateTranslation(
                    master_id=notification.id,
                    language_code=language,
                    subject=subject,
                    body=body,
                )
            )
        NotificationTemplateTranslation.objects.bulk_create(translations)


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0012_add_reservation_reminder_type"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
