# Generated by Django 3.0.14 on 2025-02-13 11:56

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_create_reservation_reminder_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplatetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='notifications.NotificationTemplate'),
        ),
    ]
