# Generated by Django 2.2.11 on 2022-04-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0092_auto_20211026_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('name', 'category'), 'verbose_name': 'equipment', 'verbose_name_plural': 'equipment'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='authentication',
            field=models.CharField(choices=[('none', 'None'), ('weak', 'Weak'), ('mid', 'Mid'), ('strong', 'Strong')], max_length=20, verbose_name='Authentication'),
        ),
    ]
