# Generated by Django 2.2.11 on 2022-03-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0092_auto_20211026_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='temporarily_closed',
            field=models.BooleanField(default=False, verbose_name='Temporarily closed'),
        ),
    ]
