# Generated by Django 2.2.11 on 2022-04-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0092_auto_20211026_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='accessibility_description',
            field=models.TextField(blank=True, verbose_name='Accessibility description'),
        ),
        migrations.AddField(
            model_name='resource',
            name='accessibility_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Accessibility description'),
        ),
        migrations.AddField(
            model_name='resource',
            name='accessibility_description_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Accessibility description'),
        ),
        migrations.AddField(
            model_name='resource',
            name='accessibility_description_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Accessibility description'),
        ),
    ]
