# Generated by Django 2.2.11 on 2022-05-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0093_add_accessibility_description_to_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('name', 'category'), 'verbose_name': 'equipment', 'verbose_name_plural': 'equipment'},
        ),
    ]
