# Generated by Django 2.2.11 on 2022-03-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0093_add_resource_temporarily_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='external_reservation_text',
            field=models.TextField(blank=True, verbose_name='External reservation free text'),
        ),
        migrations.AddField(
            model_name='resource',
            name='external_reservation_text_fi',
            field=models.TextField(blank=True, null=True, verbose_name='External reservation free text'),
        ),
        migrations.AddField(
            model_name='resource',
            name='external_reservation_text_sv',
            field=models.TextField(blank=True, null=True, verbose_name='External reservation free text'),
        ),
        migrations.AddField(
            model_name='resource',
            name='external_reservation_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='External reservation free text'),
        ),
    ]
