# Generated by Django 2.2.11 on 2022-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0094_add_external_reservation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='can_use_without_reservation',
            field=models.BooleanField(default=False, verbose_name='Can use without reservation'),
        ),
    ]
