# Generated by Django 2.2.11 on 2022-05-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0095_order_equipment_by_name_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Is period a template'),
        ),
        migrations.AddField(
            model_name='period',
            name='template_src',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=models.deletion.SET_NULL,
                                    to='resources.Period',
                                    verbose_name='Template'),
        ),
    ]
