# Generated by Django 2.2.11 on 2022-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0096_add_period_template_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='should_be_reserved_whole_day',
            field=models.BooleanField(default=False, verbose_name='Should be reserved for whole day'),
        ),
    ]
