# Generated by Django 2.2.11 on 2022-06-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0097_whole_day_reservable_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='authentication',
            field=models.CharField(choices=[('none', 'None'), ('weak', 'Weak'), ('mid', 'Mid'), ('strong', 'Strong'), ('PIKI', 'PIKI')], max_length=20, verbose_name='Authentication'),
        ),
    ]
