# Generated by Django 2.2.11 on 2022-06-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0098_add_PIKI_as_auth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceimage',
            name='type',
            field=models.CharField(choices=[('main', 'Main photo'), ('ground_plan', 'Ground plan'), ('map', 'Map'), ('other', 'Other'), ('panorama', '360 panorama')], max_length=20, verbose_name='Type'),
        ),
    ]
