# Generated by Django 2.2.11 on 2022-07-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0098_add_PIKI_as_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cancellation_min_days_in_advance',
            field=models.PositiveIntegerField(default=0, verbose_name='Reservation cancellation min. days in advance'),
        ),
        migrations.AddField(
            model_name='resource',
            name='owner_can_cancel_reservation',
            field=models.BooleanField(default=False, verbose_name='Owner can cancel manually confirmed reservation'),
        ),
    ]
