# Generated by Django 2.2.11 on 2022-07-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0099_add_panoroma_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='notification_email_addresses',
            field=models.TextField(
                blank=True,
                verbose_name='Notification email addresses separated by comma',
            ),
        ),
    ]
