# Generated by Django 2.2.11 on 2022-07-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0100_add_notification_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cancellation_min_days_in_advance',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='The customer can cancel the reservation (days) before the reservation starts.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='free_to_use',
            field=models.BooleanField(blank=True, default=True, verbose_name='The space is free of charge'),
        ),
        migrations.AddField(
            model_name='resource',
            name='owner_can_cancel_reservation',
            field=models.BooleanField(blank=True, default=False, verbose_name='Owner can cancel manually confirmed reservation'),
        ),
    ]
