# Generated by Django 2.2.1 on 2022-09-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0101_add_free_reservation_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='placement',
            field=models.CharField(blank=True, choices=[('inside', 'Inside'), ('outside', 'Outside'), ('both', 'Inside and outside')], help_text='Is the resource located outside/inside or both?', max_length=32, verbose_name='Placement'),
        ),
    ]
