# Generated by Django 2.2.11 on 2023-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0102_add_resource_placement"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="cost_center_code",
            field=models.CharField(
                default="", max_length=100, blank=True, verbose_name="Cost center code"
            ),
        ),
    ]
