# Generated by Django 2.2.11 on 2022-08-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respa_pricing', '0001_initial'),
        ('resources', '0102_add_resource_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='respa_pricing.PriceList'),
        ),
    ]
