# Generated by Django 2.2.11 on 2023-04-28 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0103_unit_cost_center_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="max_price",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="min_price",
        ),
    ]
