# Generated by Django 2.2.11 on 2023-05-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0104_auto_20230428_1040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal reservation"),
                    ("blocked", "Resource blocked"),
                    ("internal_use", "Reservation for internal use"),
                    ("for_customer", "Reservation on behalf of a customer"),
                ],
                default="normal",
                max_length=32,
                verbose_name="Type",
            ),
        ),
    ]
