# Generated by Django 2.2.11 on 2022-11-09 15:21

from django.db import migrations


def empty_existing_resource_payment_terms(apps, schema_editor):
    Resource = apps.get_model('resources', 'Resource')
    Resource.objects.exclude(payment_terms=None).update(payment_terms=None)

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0104_add_confirmed_but_not_paid_state'),
    ]

    operations = [
        migrations.RunPython(empty_existing_resource_payment_terms)
    ]
