# Generated by Django 2.2.11 on 2022-11-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0105_empty_resource_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_where_payment_terms', to='respa_pricing.RespaPaymentTerm', verbose_name='Payment terms'),
        ),
    ]
