# Generated by Django 2.2.11 on 2023-05-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0105_auto_20230509_1103"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved at"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Requested at"
            ),
        ),
    ]
