# Generated by Django 2.2.11 on 2023-06-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0106_add_requested_at_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='default_max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price displayed if no price list info attached to this resource.', max_digits=10, null=True, verbose_name='Default maximum price'),
        ),
        migrations.AddField(
            model_name='resource',
            name='default_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price displayed if no price list info attached to this resource.', max_digits=10, null=True, verbose_name='Default minimum price'),
        ),
    ]
