# Generated by Django 2.2.11 on 2023-07-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0107_auto_20230609_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='need_manual_confirmation_for_zero_price',
            field=models.BooleanField(default=False, verbose_name='Need manual confirmation when price is zero'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='default_max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price displayed if no price list info attached to this resource.', max_digits=10, null=True, verbose_name='Default max price'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='default_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price displayed if no price list info attached to this resource.', max_digits=10, null=True, verbose_name='Default min price'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='price_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('fixed', 'Fixed')], default='hourly', max_length=32, verbose_name='Price type for default prices'),
        ),
    ]
