# Generated by Django 2.2.11 on 2023-07-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0108_auto_20230711_1036"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="can_request_invoice",
            field=models.BooleanField(
                default=False, verbose_name="Customer can request payment with invoice"
            ),
        ),
    ]
