# Generated by Django 2.2.11 on 2023-07-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0109_add_resource_can_require_invoice_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="company_address_city",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Company address city"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="company_address_street",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Company address street"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="company_address_zip",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Company address zip"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="company_email_address",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Company email address"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="company_phone_number",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Company phone number"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="invoice_requested_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Invoice requested by customer",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("cancelled", "cancelled"),
                    ("confirmed", "confirmed"),
                    ("denied", "denied"),
                    ("requested", "requested"),
                    ("invoice_requested", "invoice requested"),
                    ("waiting_for_payment", "waiting for payment"),
                ],
                default="created",
                max_length=32,
                verbose_name="State",
            ),
        ),
    ]
