# Generated by Django 2.2.11 on 2023-07-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0110_add_reservation_invoice_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='invoice_requested',
            field=models.BooleanField(default=False, verbose_name='Invoice requested by customer'),
        ),
    ]
