# Generated by Django 2.2.11 on 2023-07-21 06:49

from django.db import migrations

COMPANY_FIELDS = (
    "company_email_address",
    "company_phone_number",
    "company_address_street",
    "company_address_zip",
    "company_address_city",
)


def forwards(apps, schema_editor):
    ReservationMetadataField = apps.get_model("resources", "ReservationMetadataField")

    existing_fields = set(
        ReservationMetadataField.objects.values_list("field_name", flat=True)
    )

    fields = [
        ReservationMetadataField(field_name=field)
        for field in COMPANY_FIELDS
        if field not in existing_fields
    ]

    if fields:
        ReservationMetadataField.objects.bulk_create(fields)


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0111_reservation_invoice_requested"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
