# Generated by Django 2.2.11 on 2023-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0112_add_company_metadata_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="invoice_approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Invoice approved by admin at"
            ),
        ),
    ]
