# Generated by Django 2.2.11 on 2023-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0113_add_invoice_requested_at_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="invoice_generated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Invoice XML document generated at"
            ),
        ),
    ]
