# Generated by Django 2.2.11 on 2023-08-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0114_add_invoice_generated_at_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="sap_cost_center_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="SAP Cost center code",
            ),
        ),
    ]
