# Generated by Django 2.2.11 on 2023-08-07 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0115_unit_sap_cost_center_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="sap_sales_organization",
            field=models.CharField(
                blank=True,
                max_length=4,
                validators=[django.core.validators.MinLengthValidator(4)],
                verbose_name="SAP Sales Organization code",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="cost_center_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="CeePos Cost center code",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="sap_cost_center_code",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="SAP Cost center code"
            ),
        ),
    ]
