# Generated by Django 2.2.11 on 2023-10-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0116_add_sap_sales_org_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_method",
                    models.CharField(
                        choices=[
                            ("pincode", "Pincode"),
                            ("mobile_app", "Mobile app"),
                            ("physical_key", "Physical keykkeycard"),
                            (
                                "staff_member",
                                "Staff member (e.g. security guard or janitor)",
                            ),
                            ("open_door", "Door is always open"),
                        ],
                        max_length=15,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="resource",
            name="access_methods",
            field=models.ManyToManyField(
                blank=True, to="resources.ResourceAccess", verbose_name="Access methods"
            ),
        ),
    ]
