# Generated by Django 2.2.11 on 2023-10-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0116_add_sap_sales_org_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="sap_unit_id",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="SAP Unit ID"
            ),
        ),
    ]
