# Generated by Django 2.2.11 on 2023-10-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0117_unit_sap_unit_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="sap_income_account_identifier",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="SAP Income Account Identifier"
            ),
        ),
    ]
