# Generated by Django 2.2.11 on 2023-11-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_sapincomeaccount_sapmaterialcode"),
        ("resources", "0117_unit_sap_unit_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="sap_income_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="payments.SAPIncomeAccount",
                verbose_name="SAP Income Account",
            ),
        ),
    ]
