# Generated by Django 2.2.11 on 2023-10-31 09:54

from django.db import migrations

ACCESS_METHODS = (
    "pincode",
    "mobile_app",
    "physical_key",
    "staff_member",
    "open_door",
)


def add_access_methods(apps, schema_editor):
    ResourceAccess = apps.get_model("resources.ResourceAccess")

    ResourceAccess.objects.bulk_create(
        [ResourceAccess(access_method=method) for method in ACCESS_METHODS],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0117_add_resource_access"),
    ]

    operations = [
        migrations.RunPython(add_access_methods, reverse_code=migrations.RunPython.noop)
    ]
