# Generated by Django 2.2.11 on 2023-10-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0118_unit_sap_income_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="invoice_marked_ready_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the invoice was marked as ready to be sent to SAP",
                null=True,
                verbose_name="Invoice marked ready at",
            ),
        ),
    ]
