# Generated by Django 2.2.11 on 2023-11-17 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0118_create_default_access_methods"),
        ("resources", "0119_reservation_invoice_marked_ready_at"),
    ]

    operations = []
