# Generated by Django 2.2.11 on 2023-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0120_merge_20231117_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='access_method',
            field=models.CharField(choices=[('pincode', 'Pincode'), ('mobile_app', 'Mobile app'), ('physical_key', 'Traditional key/keycard'), ('staff_member', 'Security guard/janitor'), ('open_door', 'Door open')], max_length=15, unique=True),
        ),
    ]
