# Generated by Django 2.2.11 on 2024-12-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0121_auto_20231218_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceaccess',
            options={'verbose_name': 'Resource access method', 'verbose_name_plural': 'Resource access methods'},
        ),
    ]
