# Generated by Django 2.2.11 on 2024-12-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0122_auto_20241218_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Reminder sent'),
        ),
    ]
