# Generated by Django 2.2.11 on 2025-01-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0123_reservation_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive purposes are not shown in the Respa admin.', verbose_name='Active'),
        ),
    ]
