# Generated by Django 2.2.11 on 2025-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0124_purpose_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofuse',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive terms are not shown in the Respa admin.', verbose_name='Active'),
        ),
    ]
