# Generated by Django 2.2.11 on 2025-01-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0125_termsofuse_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive resource types are not shown in the Respa admin.', verbose_name='Active'),
        ),
    ]
