# Generated by Django 2.2.11 on 2025-01-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0126_resourcetype_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmetadataset',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive metadata sets are not shown in the resource form in Respa admin.', verbose_name='Active'),
        ),
    ]
