# Generated by Django 2.2.11 on 2025-01-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0127_reservationmetadataset_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive equipment is not shown in the Respa admin.', verbose_name='Active'),
        ),
    ]
