# Generated by Django 2.2.11 on 2025-01-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0128_equipment_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='people_capacity',
            new_name='people_capacity_lower',
        ),
    ]
