# Generated by Django 2.2.11 on 2025-01-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0129_rename_people_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='people_capacity_upper',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='People capacity upper limit'),
        ),
    ]
