# Generated by Django 3.2.25 on 2025-02-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0131_alter_unit_cost_center_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='closed',
            field=models.BooleanField(default=False, null=True, verbose_name='Closed'),
        ),
    ]
