# Generated by Django 4.2.19 on 2025-12-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0133_alter_equipment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='cost_center_code',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='CeePos Cost center code'),
        ),
        migrations.AlterField(
            model_name='unitauthorization',
            name='level',
            field=models.CharField(choices=[('admin', 'unit administrator'), ('manager', 'unit manager'), ('viewer', 'unit viewer')], max_length=50, verbose_name='authorization level'),
        ),
        migrations.AlterField(
            model_name='unitgroupauthorization',
            name='level',
            field=models.CharField(choices=[('admin', 'unit group administrator')], max_length=50, verbose_name='authorization level'),
        ),
    ]
