# Generated by Django 2.2.11 on 2023-07-27 09:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RespaInstruction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Ordering")),
                ("title", models.CharField(max_length=264, verbose_name="Title")),
                (
                    "applicable_for",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")],
                        default="user",
                        max_length=32,
                        verbose_name="Applicable for",
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Content"
                    ),
                ),
                (
                    "content_fi",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        null=True, verbose_name="Content"
                    ),
                ),
                (
                    "content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        null=True, verbose_name="Content"
                    ),
                ),
                (
                    "content_sv",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        null=True, verbose_name="Content"
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Instruction",
                "verbose_name_plural": "Instructions",
                "ordering": ("order",),
            },
        ),
    ]
