# Generated by Django 2.2.11 on 2022-09-05 08:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespaInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=264, verbose_name='Title')),
                ('applicable_for', models.CharField(choices=[('admin', 'Admin'), ('applicant', 'Applicant')], default='applicant', max_length=32, verbose_name='Applicable for')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_fi', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_sv', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
