# Generated by Django 4.2.19 on 2025-02-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_instructions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respainstruction',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='respainstruction',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='respainstruction',
            name='content_fi',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='respainstruction',
            name='content_sv',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
    ]
